### ISSUE TITLE
Support a depth limit

### ISSUE THREAD

**Issue by TylerLeonhardt** [mganss/Glob.cs#1]
It would be nice if Glob.cs could support a depth limit so that it doesn't go on infinitely. The Cancel method is nice but seems to require another thread in order to issue that cancellation.

**Comment by mganss** [comment]
Do you already have a specific idea how this should work? Relative to which folder should the limit be calculated? Do you know an example of another library (perhaps in another language) where this is implemented?

**Comment by TylerLeonhardt** [comment]
yeah it would be either relative to the `**`. or relative to the root. Whichever is easier probably.

I'm thinking it could be passed into the Expand function.
```csharp
var glob = new Glob("/my/path/**/*");
glob.Expand(depthLimit: 25);
```

I can't seem to find any sort of example on this sadly. I'm surprised this is not a common feature on globbing the filesystem since a Denial of Service is possible with this type of request.

**Comment by mganss** [comment]
I've added an option to limit the depth up to which a `**` can expand. Also, extracted options into their own class.
