### ISSUE TITLE
Support CancellationToken for cancelling

### ISSUE THREAD

**Issue by TylerLeonhardt** [mganss/Glob.cs#2]
Another thing I thought about was allowing `Expand` to take in a `CancellationToken`. This would allow for the use of:

https://docs.microsoft.com/en-us/dotnet/api/system.threading.cancellationtokensource.cancelafter?view=netframework-4.7.2

and other cancellation scenarios. From what I could tell, today you have to start the `Expand` in one thread and cancel it in another manually. Using the CancellationToken seems like a C#-y way of cancelling a currently expanding Glob.

**Comment by mganss** [comment]
Expansion is performed lazily, i.e. you can cancel from the same thread by stopping the enumeration, e.g.
```C#
var sw = Stopwatch.StartNew();
var files = Glob.Expand("...").TakeWhile(f => sw.ElapsedMilliseconds < 10000).ToList();
```

**Comment by TylerLeonhardt** [comment]
Very good point. Thanks for the clarity. This should work with a `CancellationToken` just fine then:

```csharp
var files = Glob.Expand("...").TakeWhile(f => token.IsCancellationRequested).ToList();
```

guess we can close this - but I'd still love to see #1 happen someday 😄
