### ISSUE TITLE
Expand returns empty when an existing directory is specified and dirOnly is false

### ISSUE THREAD

**Issue by capyvara** [mganss/Glob.cs#40]
I'm not sure if this is the intended behaviour.

To reproduce:
ExpandNames("/tmp/abcd") where /tmp/abcd exists and is a directory.

dirOnly == true mean **only directories** will be returned, so dirOnly = false should include **files and directories**.

Maybe if can be fixed by changing line 192:
`fsi = dirOnly || fileSystem.Directory.Exists(path) ? (IFileSystemInfo)fileSystem.DirectoryInfo.FromDirectoryName(path) : fileSystem.FileInfo.FromFileName(path);`

**Comment by mganss** [comment]
Thanks for catching this.
